import ViewState from './state/view';
import CreateState from './state/create';
import ViewCountry from './country/view';
import CreateCountry from './country/create';
import ViewSupplierLocationMaster from './supplierLocationMaster/view';
import CreateSupplierLocationMaster from './supplierLocationMaster/create';
import CreateMaster from './supplierMaster/create';
import ViewSuppliersList from './supplierMaster/view';
import CreateGodown from './godown/create';
import ViewGodown from './godown/view';
import CreateSection from './section/create';
import ViewSection from './section/view';
import CreateCompany from './companySetUp/create';

import ViewGroupList from './groupList/view';
import CreateGroupList from './groupList/create';
import ViewRackList from './rackList/view';
import CreateRackList from './rackList/create';

import CreateApprovalUserLimit from './approvalUserLimit/create';
import ViewApprovalUserLimit from './approvalUserLimit/view';
import MainComponet from './index';

interface MenuItem {
  label: string;
  key: string;
  title?: string;
  component: any;
  path: any;
  subMenu?: any;
  hidden?: boolean;
  mainkey?: string;
  isButton?: any;
  buttonLink?: string;
  isback?: boolean;
  buttonTitle?: string;
  element?: any;
  identity?: string;
  isEditIcon?: boolean;
}

export const General_Sub_Menu: MenuItem[] = [
  {
    label: 'Country',
    key: '/view-country',
    mainkey: '/view-country',
    path: '/view-country',
    component: ViewCountry,
    element: <MainComponet />,
    buttonLink: '/create-country',
    buttonTitle: 'Add Country',
    identity: 'generalsetup',
  },
  {
    label: 'Country',
    key: '/create-country',
    path: '/create-country',
    mainkey: '/view-country',
    title: 'Create Country',
    element: <MainComponet />,
    component: CreateCountry,
    hidden: true,
    isback: true,
    identity: 'generalsetup',
  },
  {
    label: 'Country',
    key: '/edit-country',
    path: '/edit-country',
    mainkey: '/view-country',
    title: 'Create Country',
    element: <MainComponet />,
    component: CreateCountry,
    hidden: true,
    isback: true,
    identity: 'generalsetup',
  },
  {
    label: 'State',
    key: '/view-state',
    mainkey: '/view-state',
    path: '/view-state',
    component: ViewState,
    element: <MainComponet />,
    buttonLink: '/create-state',
    buttonTitle: 'Add State',

    identity: 'generalsetup',
  },
  {
    label: 'State',
    key: '/create-state',
    path: '/create-state',
    mainkey: '/view-state',
    title: 'Create State',
    element: <MainComponet />,
    component: CreateState,
    hidden: true,
    isback: true,
    identity: 'generalsetup',
  },
  {
    label: 'State',
    key: '/edit-state',
    path: '/edit-state',
    mainkey: '/view-state',
    title: 'Create State',
    element: <MainComponet />,
    component: CreateState,
    hidden: true,
    isback: true,
    identity: 'generalsetup',
  },
  {
    label: 'Company',
    key: '/create-company',
    path: '/create-company',
    mainkey: '/view-company',
    title: 'Company',
    element: <MainComponet />,
    component: CreateCompany,
    identity: 'generalsetup',
    hidden: true,
  },
  {
    label: 'Company',
    key: '/edit-company',
    path: '/edit-company',
    mainkey: '/view-company',
    title: 'Company',
    element: <MainComponet />,
    component: CreateCompany,
    identity: 'generalsetup',
    hidden: true,
  },
  {
    label: 'Company',
    key: '/view-company',
    path: '/view-company',
    mainkey: '/view-company',
    title: 'Company',
    element: <MainComponet />,
    component: CreateCompany,
    identity: 'generalsetup',
    buttonLink: '/edit-company',
    buttonTitle: 'Edit Company Details',
    isEditIcon: true,
  },
  {
    label: 'Godown',
    key: '/view-godown',
    mainkey: '/view-godown',
    path: '/view-godown',
    component: ViewGodown,
    element: <MainComponet />,
    buttonLink: '/create-godown',
    buttonTitle: 'Add Godown',
    identity: 'generalsetup',
  },
  {
    label: 'Create Godown',
    key: '/create-godown',
    path: '/create-godown',
    mainkey: '/view-godown',
    title: 'Create Godown',
    element: <MainComponet />,
    component: CreateGodown,
    hidden: true,
    isback: true,
    identity: 'generalsetup',
  },
  {
    label: 'Edit Godown',
    key: '/edit-godown',
    path: '/edit-godown',
    mainkey: '/view-godown',
    title: 'Create Godown',
    element: <MainComponet />,
    component: CreateGodown,
    hidden: true,
    isback: true,
  },
  {
    label: 'Section',
    key: '/view-section',
    mainkey: '/view-section',
    path: '/view-section',
    component: ViewSection,
    element: <MainComponet />,
    buttonLink: '/create-section',
    buttonTitle: 'Add Section',
    identity: 'generalsetup',
  },
  {
    label: 'Create Section',
    key: '/create-section',
    path: '/create-section',
    mainkey: '/view-section',
    title: 'Create Section',
    element: <MainComponet />,
    component: CreateSection,
    hidden: true,
    isback: true,
    identity: 'generalsetup',
  },
  {
    label: 'Edit Section',
    key: '/edit-section',
    path: '/edit-section',
    mainkey: '/view-section',
    title: 'Edit Section',
    element: <MainComponet />,
    component: CreateSection,
    hidden: true,
    isback: true,
    identity: 'generalsetup',
  },
  {
    label: 'Supplier Location',
    key: '/create-supplier-location',
    path: '/create-supplier-location',
    mainkey: '/view-supplier-location',
    title: 'Create Supplier Location',
    element: <MainComponet />,
    component: CreateSupplierLocationMaster,
    hidden: true,
    isback: true,
    identity: 'generalsetup',
  },
  {
    label: 'Supplier Location',
    key: '/edit-supplier-location',
    path: '/edit-supplier-location',
    mainkey: '/view-supplier-location',
    title: 'Create Supplier Location',
    element: <MainComponet />,
    component: CreateSupplierLocationMaster,
    hidden: true,
    isback: true,
    identity: 'generalsetup',
  },
  // {
  //   label: 'Approval User Limit ',
  //   key: '/view-inventory-approval-user-limit',
  //   mainkey: '/view-inventory-approval-user-limit',
  //   path: '/view-inventory-approval-user-limit',
  //   component: ViewApprovalUserLimit,
  //   element: <MainComponet />,
  //   buttonLink: '/create-inventory-approval-user-limit',
  //   buttonTitle: 'Add User',
  //   identity: 'generalsetup',
  // },
  // {
  //   label: 'Approval User Limit',
  //   key: '/create-inventory-approval-user-limit',
  //   path: '/create-inventory-approval-user-limit',
  //   mainkey: '/view-inventory-approval-user-limit',
  //   title: 'Create Approval User Limit',
  //   element: <MainComponet />,
  //   component: CreateApprovalUserLimit,
  //   hidden: true,
  //   isback: true,
  //   identity: 'generalsetup',
  // },
  // {
  //   label: 'Approval User Limit',
  //   key: '/edit-inventory-approval-user-limit',
  //   path: '/edit-inventory-approval-user-limit',
  //   mainkey: '/view-inventory-approval-user-limit',
  //   title: 'Create Supplier Approval User Limit',
  //   element: <MainComponet />,
  //   component: CreateApprovalUserLimit,
  //   hidden: true,
  //   isback: true,
  //   identity: 'generalsetup',
  // },
  {
    label: 'Supplier List',
    key: '/view-supplier-list',
    mainkey: '/view-supplier-list',
    path: '/view-supplier-list',
    component: ViewSuppliersList,
    element: <MainComponet />,
    buttonLink: '/create-supplier-list',
    buttonTitle: 'Add Supplier',
    identity: 'generalsetup',
  },
  {
    label: 'Create Supplier',
    key: '/create-supplier-list',
    path: '/create-supplier-list',
    mainkey: '/view-supplier-list',
    title: 'Create Supplier',
    element: <MainComponet />,
    component: CreateMaster,
    hidden: true,
    isback: true,
    identity: 'generalsetup',
  },
  {
    label: 'Edit Supplier',
    key: '/edit-supplier',
    path: '/edit-supplier',
    mainkey: '/view-supplier-list',
    title: 'Create Supplier Location',
    element: <MainComponet />,
    component: CreateMaster,
    hidden: true,
    isback: true,
    identity: 'generalsetup',
  },
  {
    label: 'Supplier Location',
    key: '/view-supplier-location',
    mainkey: '/view-supplier-location',
    path: '/view-supplier-location',
    component: ViewSupplierLocationMaster,
    element: <MainComponet />,
    buttonLink: '/create-supplier-location',
    buttonTitle: 'Add Supplier Location',
    identity: 'generalsetup',
  },
  {
    label: 'Supplier Location',
    key: '/create-supplier-location',
    path: '/create-supplier-location',
    mainkey: '/view-supplier-location',
    title: 'Create Supplier Location',
    element: <MainComponet />,
    component: CreateSupplierLocationMaster,
    hidden: true,
    isback: true,
    identity: 'generalsetup',
  },
  {
    label: 'Supplier Location',
    key: '/edit-supplier-location',
    path: '/edit-supplier-location',
    mainkey: '/view-supplier-location',
    title: 'Create Supplier Location',
    element: <MainComponet />,
    component: CreateSupplierLocationMaster,
    hidden: true,
    isback: true,
  },
  {
    label: 'Groups',
    key: '/view-groups',
    mainkey: '/view-groups',
    path: '/view-groups',
    component: ViewGroupList,
    element: <MainComponet />,
    buttonLink: '/create-groups',
    buttonTitle: 'Add Groups',
    identity: 'generalsetup',
  },
  {
    label: 'Groups',
    key: '/create-groups',
    path: '/create-groups',
    mainkey: '/view-groups',
    title: 'Create Groups',
    element: <MainComponet />,
    component: CreateGroupList,
    hidden: true,
    isback: true,
    identity: 'generalsetup',
  },
  {
    label: 'Groups',
    key: '/edit-groups',
    path: '/edit-groups',
    mainkey: '/view-groups',
    title: 'Create Groups',
    element: <MainComponet />,
    component: CreateGroupList,
    hidden: true,
    isback: true,
  },
  {
    label: 'Racks',
    key: '/view-racks',
    mainkey: '/view-racks',
    path: '/view-racks',
    component: ViewRackList,
    element: <MainComponet />,
    buttonLink: '/create-racks',
    buttonTitle: 'Add Racks',
    identity: 'generalsetup',
  },
  {
    label: 'Racks',
    key: '/create-racks',
    path: '/create-racks',
    mainkey: '/view-racks',
    title: 'Create Racks',
    element: <MainComponet />,
    component: CreateRackList,
    hidden: true,
    isback: true,
    identity: 'generalsetup',
  },
  {
    label: 'Racks',
    key: '/edit-racks',
    path: '/edit-racks',
    mainkey: '/view-racks',
    title: 'Create Racks',
    element: <MainComponet />,
    component: CreateRackList,
    hidden: true,
    isback: true,
  },
];
