import ViewDesignation from './Designation/view';
import CreateDesignation from './Designation/create';
import CreateEmployeecategory from './EmployeeCategory/create';
import ViewEmployeecategory from './EmployeeCategory/view';
import CreateEmployeetype from './EmployeeType/create';
import ViewEmployeetype from './EmployeeType/view';
import ViewLeavetypemaster from './LeaveTypeMaster/view';
import CreateLeavetypemaster from './LeaveTypeMaster/create';
import ViewOvertimecategory from './OvertimeCategoryDetails/viewOverTimeCategoryDetails';
import CreateOvertimeCategory from './OvertimeCategoryDetails/create';
import CreateQualification from './Qualification/create';
import ViewQualification from './Qualification/view';
import CreateSalaryParamterMaster from './SalaryParamterMaster/create';
import ViewSalaryParamterMaster from './SalaryParamterMaster/view';
import CreateShiftMaster from './ShiftMaster/create';
import ViewShiftMaster from './ShiftMaster/view';
import MainComponent from './index';

import ViewEmployeePayCategory from './EmployeePayCategory/view';
import CreateEmployeePayCategory from './EmployeePayCategory/create';

interface MenuItem {
  label: string;
  key: string;
  title?: string;
  component: any;
  path: any;
  subMenu?: any;
  hidden?: boolean;
  mainkey?: string;
  isButton?: any;
  buttonLink?: string;
  isback?: boolean;
  buttonTitle?: string;
  element?: any;
  identity: string;
  subidentity?: string;
  doctype?: string;
}

export const Employee_Sub_Menu: MenuItem[] = [
  {
    label: 'Qualification',
    key: '/view-qualification',
    mainkey: '/view-qualification',
    path: '/view-qualification',
    doctype: 'Qualification',
    component: ViewQualification,
    element: <MainComponent />,
    buttonLink: '/create-qualification',
    buttonTitle: 'Add Qualification',
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Create Qualification',
    key: '/create-qualification',
    mainkey: '/view-qualification',
    path: '/create-qualification',
    component: CreateQualification,
    doctype: 'Qualification',
    element: <MainComponent />,
    hidden: true,
    isback: true,
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Edit Qualification',
    key: '/edit-qualification',
    mainkey: '/view-qualification',
    path: '/edit-qualification',
    component: CreateQualification,
    doctype: 'Qualification',
    element: <MainComponent />,
    hidden: true,
    isback: true,
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Employee Type',
    key: '/view-employee-type',
    mainkey: '/view-employee-type',
    path: '/view-employee-type',
    component: ViewEmployeetype,
    element: <MainComponent />,
    buttonLink: '/create-employee-type',
    buttonTitle: 'Add Employee Type',
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Create Employee Type',
    key: '/create-employee-type',
    mainkey: '/view-employee-type',
    path: '/create-employee-type',
    component: CreateEmployeetype,
    element: <MainComponent />,
    hidden: true,
    isback: true,
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Edit Employee Type',
    key: '/edit-employment-type',
    mainkey: '/view-employee-type',
    path: '/edit-employment-type',
    component: CreateEmployeetype,
    element: <MainComponent />,
    hidden: true,
    isback: true,
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Designation',
    key: '/view-designation',
    mainkey: '/view-designation',
    path: '/view-designation',
    component: ViewDesignation,
    element: <MainComponent />,
    buttonLink: '/create-designation',
    buttonTitle: 'Add Designation',
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Create Designation',
    key: '/create-designation',
    mainkey: '/view-designation',
    path: '/create-designation',
    component: CreateDesignation,
    element: <MainComponent />,
    hidden: true,
    isback: true,
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Edit Designation',
    key: '/edit-designation',
    mainkey: '/view-designation',
    path: '/edit-designation',
    component: CreateDesignation,
    element: <MainComponent />,
    hidden: true,
    isback: true,
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Salary Parameter',
    key: '/view-salary-parameter',
    mainkey: '/view-salary-parameter',
    path: '/view-salary-parameter',
    component: ViewSalaryParamterMaster,
    element: <MainComponent />,
    buttonLink: '/create-salary-parameter',
    buttonTitle: 'Add Salary Parameter',
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Create Salary Parameter',
    key: '/create-salary-parameter',
    mainkey: '/view-salary-parameter',
    path: '/create-salary-parameter',
    component: CreateSalaryParamterMaster,
    element: <MainComponent />,
    hidden: true,
    isback: true,
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Edit Salary Parameter',
    key: '/edit-salary-parameter',
    mainkey: '/view-salary-parameter',
    path: '/edit-salary-parameter',
    component: CreateSalaryParamterMaster,
    element: <MainComponent />,
    hidden: true,
    isback: true,
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Shift Master',
    key: '/view-shift-master',
    mainkey: '/view-shift-master',
    path: '/view-shift-master',
    component: ViewShiftMaster,
    element: <MainComponent />,
    buttonLink: '/create-shift-master',
    buttonTitle: 'Add Shift Master',
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Create Shift Master',
    key: '/create-shift-master',
    mainkey: '/view-shift-master',
    path: '/create-shift-master',
    component: CreateShiftMaster,
    element: <MainComponent />,
    hidden: true,
    isback: true,
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Edit Shift Master',
    key: '/edit-shift-master',
    mainkey: '/view-shift-master',
    path: '/edit-shift-master',
    component: CreateShiftMaster,
    element: <MainComponent />,
    hidden: true,
    isback: true,
    identity: 'masterdata',
  },

  {
    label: 'Leave Type',
    key: '/view-leave-type-master',
    mainkey: '/view-leave-type-master',
    path: '/view-leave-type-master',
    component: ViewLeavetypemaster,
    element: <MainComponent />,
    buttonLink: '/create-leave-type-master',
    buttonTitle: 'Add Leave Type',
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Create Leave Type',
    key: '/create-leave-type-master',
    mainkey: '/view-leave-type-master',
    path: '/create-leave-type-master',
    component: CreateLeavetypemaster,
    element: <MainComponent />,
    hidden: true,
    isback: true,
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Edit Leave Type',
    key: '/edit-leave-type-master',
    mainkey: '/view-leave-type-master',
    path: '/edit-leave-type-master',
    component: CreateLeavetypemaster,
    element: <MainComponent />,
    hidden: true,
    isback: true,
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Week off Category',
    key: '/view-employee-week-off-category',
    mainkey: '/view-employee-week-off-category',
    path: '/view-employee-week-off-category',
    component: ViewEmployeecategory,
    element: <MainComponent />,
    buttonLink: '/create-week-off-employee-category',
    buttonTitle: 'Add Week off Category',
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Create Week off Category',
    key: '/create-week-off-employee-category',
    mainkey: '/view-employee-week-off-category',
    path: '/create-week-off-employee-category',
    component: CreateEmployeecategory,
    element: <MainComponent />,
    hidden: true,
    isback: true,
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Edit Week off Category',
    key: '/edit-week-off-category',
    mainkey: '/view-employee-week-off-category',
    path: '/edit-week-off-category',

    component: CreateEmployeecategory,
    element: <MainComponent />,
    hidden: true,
    isback: true,
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Overtime Category',
    key: '/view-overtime-category',
    mainkey: '/view-overtime-category',
    path: '/view-overtime-category',
    component: ViewOvertimecategory,
    element: <MainComponent />,
    buttonLink: '/create-overtime-category',
    buttonTitle: 'Add Overtime Category',
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Create Overtime Category',
    key: '/create-overtime-category',
    mainkey: '/view-overtime-category',
    path: '/create-overtime-category',
    component: CreateOvertimeCategory,
    element: <MainComponent />,
    hidden: true,
    isback: true,
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Edit Overtime Category',
    key: '/edit-overtime-category',
    mainkey: '/view-overtime-category',
    path: '/edit-overtime-category',
    component: CreateOvertimeCategory,
    element: <MainComponent />,
    hidden: true,
    isback: true,
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Employee Category',
    key: '/view-employee-category',
    mainkey: '/view-employee-category',
    path: '/view-employee-category',
    component: ViewEmployeePayCategory,
    element: <MainComponent />,
    buttonLink: '/create-employee-category',
    buttonTitle: 'Add Employee Category',
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Create Employee Category',
    key: '/create-employee-category',
    mainkey: '/view-employee-category',
    path: '/create-employee-category',
    component: CreateEmployeePayCategory,
    element: <MainComponent />,
    hidden: true,
    isback: true,
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
  {
    label: 'Edit Employee Category',
    key: '/edit-employee-category',
    mainkey: '/view-employee-category',
    path: '/edit-employee-category',
    component: CreateEmployeePayCategory,
    element: <MainComponent />,
    hidden: true,
    isback: true,
    identity: 'masterdata',
    subidentity: 'employeesettings',
  },
];
